version: '3.8'

services:
  speak-text-redis:
    image: redis:7.2
    container_name: speak-text-redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    command: ["redis-server", "--requirepass", "1234"]
    restart: always

  speak-text-mysql:
    image: mysql:8.0
    container_name: speak-text-mysql
    ports:
      - "3304:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: speakText
      MYSQL_TIMEZONE: Asia/Seoul
      LANG: ko_KR.UTF-8
    restart: always
    command: --default-time-zone='+09:00'
